

stages:
  - lints_test
  - test
  - build
  - deploy

.android_docker_image:
  image: cirrusci/flutter:3.7.7
  before_script:
    - echo "$FIREBASE_OPTIONS_BASE64" | base64 -di > lib/firebase_options.dart
    - echo "$DESKTOP_CREDENTIALS_BASE64" | base64 -di > lib/desktop_credentials.dart
    - echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -di > android/app/google-services.json
    - echo "$GOOGLE_SERVICES_PLIST_IOS_BASE64" | base64 -di > ios/Runner/GoogleService-Info.plist
    - echo "$GOOGLE_SERVICES_PLIST_MACOS_BASE64" | base64 -di > macos/Runner/GoogleService-Info.plist
    - echo "$WEB_INDEX_HTML_BASE64" | base64 -di > web/index.html
    - flutter clean
    - flutter pub get



test:
  extends: .android_docker_image
  stage: test
  script:
    - flutter test

lints_test:
  extends: .android_docker_image
  stage: lints_test

  script:
    - flutter pub get
    - dart analyze --fatal-infos

android_build_apk:
  stage: build
  extends: .android_docker_image
  before_script:
    - echo "$FIREBASE_OPTIONS_BASE64" | base64 -di > lib/firebase_options.dart
    - echo "$DESKTOP_CREDENTIALS_BASE64" | base64 -di > lib/desktop_credentials.dart
    - echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -di > android/app/google-services.json
    - flutter clean
    - flutter pub get
  script:
    - file='VERSION'
    - fileData=`cat $file`
    - IFS='.'
    - read -a versionValue <<< "$fileData"
    - buildNumber=$(expr `expr ${versionValue[0]} \* 1000000` + `expr ${versionValue[1]} \* 10000` + ${CI_PIPELINE_IID})
    - IFS=''
    - buildName="${versionValue[0]}.${versionValue[1]}.$CI_PIPELINE_IID"
    - echo "Genrating android build $buildName $buildNumber"
    - flutter build apk --release --build-number=$buildNumber --build-name=$buildName
    - mv build/app/outputs/apk/release/ProjectUnity*.apk .
  artifacts:
    paths:
      - ProjectUnity*.apk
  when: manual

android_build_aab:
  stage: build
  extends: .android_docker_image
  before_script:
    - echo "$FIREBASE_OPTIONS_BASE64" | base64 -di > lib/firebase_options.dart
    - echo "$DESKTOP_CREDENTIALS_BASE64" | base64 -di > lib/desktop_credentials.dart
    - echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -di > android/app/google-services.json
    - flutter clean
    - flutter pub get
  script:
    - file='VERSION'
    - fileData=`cat $file`
    - IFS='.'
    - read -a versionValue <<< "$fileData"
    - buildNumber=$(expr `expr ${versionValue[0]} \* 1000000` + `expr ${versionValue[1]} \* 10000` + ${CI_PIPELINE_IID})
    - IFS=''
    - buildName="${versionValue[0]}.${versionValue[1]}.$CI_PIPELINE_IID"
    - echo "Genrating android build $buildName $buildNumber"
    - flutter build appbundle --build-number=$buildNumber --build-name=$buildName
    - mv build/app/outputs/bundle/release/app-release.aab .
  artifacts:
    paths:
      - app-release.aab
  when: manual


deploy_internal_android:
  stage: deploy
  extends: .android_docker_image
  before_script:
    - echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -di > android/app/google-services.json
    - file='VERSION'
    - fileData=`cat $file`
    - IFS='.'
    - read -a versionValue <<< "$fileData"
    - buildNumber=$(expr `expr ${versionValue[0]} \* 1000000` + `expr ${versionValue[1]} \* 10000` + ${CI_PIPELINE_IID})
    - IFS=''
    - buildName="${versionValue[0]}.${versionValue[1]}.$CI_PIPELINE_IID"
    - cd android
    - apt-get -qq update
    - apt-get install -qqy --no-install-recommends build-essential ruby-full
    - gem install bundler fastlane
    - echo $APKSIGN_KEYSTORE_BASE64 | base64 -di > release.jks
    - export APKSIGN_KEYSTORE=`pwd`/release.jks
    - echo $APP_PLAY_SERVICE_JSON > ~/google_play_api_key.json
  script:
    - bundle exec fastlane supply init --track internal
    - bundle exec fastlane upload_internal versionName:$buildName versionCode:$buildNumber
  only:
    - main

deploy_web:
  extends: .android_docker_image
  stage: deploy
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - echo "$WEB_INDEX_HTML_BASE64" | base64 -di > web/index.html
    - apt-get update && apt-get -y install --no-install-recommends awscli
  script:
    - flutter pub get
    - flutter build web
    - aws s3 sync build/web/ s3://$AWS_S3_BUCKET_NAME
  only:
    - main