name: projectunity
description: A new Flutter project.
publish_to: 'none'


version: 1.0.2+2

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.24.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.5.1
  collection: ^1.19.0
  connectivity_plus: ^6.1.1
  device_info_plus: ^11.2.0
  equatable: ^2.0.7
  freezed: ^2.5.7
  freezed_annotation: ^2.4.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.2.0
  firebase_storage: ^12.3.7
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.10
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  go_router: ^14.6.2
  http: ^1.2.2
  injectable: ^2.5.0
  intl: any
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  oauth2: ^2.0.3
  package_info_plus: ^8.1.2
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  sticky_headers: ^0.3.0+2
  table_calendar: ^3.1.3
  url_launcher: ^6.3.1
  window_to_front: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^4.0.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  flutter_gen_runner:





flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_light.ttf
        - asset: assets/fonts/inter_medium.ttf
        - asset: assets/fonts/inter_semi_bold.ttf


    - family: poppins
      fonts:

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic



