name: projectunity
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.2
  collection: ^1.17.0
  connectivity_plus: ^3.0.5
  device_info_plus: ^8.2.1
  equatable: ^2.0.5
  event_bus: ^2.0.0
  expandable: ^5.0.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.3.1
  firebase_storage: ^11.1.1
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  get_it: ^7.3.0
  google_sign_in: ^6.1.4
  go_router: ^6.5.8
  http: ^0.13.5
  intl: ^0.17.0
  injectable: ^2.1.1
  image_picker: ^0.8.7+3
  json_annotation: ^4.8.1
  oauth2: ^2.0.1
  package_info_plus: ^3.1.2
  simple_gesture_detector:
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  sticky_headers: ^0.3.0+2
  table_calendar: ^3.0.7
  url_launcher: ^6.1.11
  uuid: ^3.0.6
  window_to_front: ^0.0.3





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mockito: ^5.4.0



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_light.ttf
        - asset: assets/fonts/inter_medium.ttf
        - asset: assets/fonts/inter_semi_bold.ttf

