name: projectunity
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^3.1.17
  connectivity_plus: ^2.3.7
  device_info_plus: ^6.0.0
  equatable: ^2.0.5
  event_bus: ^2.0.0
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  flutter_bloc: ^8.1.1
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.2.1
  intl:
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  package_info_plus: ^2.0.0
  provider: ^6.0.3
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  sticky_headers: ^0.3.0
  uuid: ^3.0.6
  table_calendar: ^3.0.7
  mockito: ^5.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  injectable_generator:
  mockito:



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_light.ttf
        - asset: assets/fonts/inter_medium.ttf
        - asset: assets/fonts/inter_semi_bold.ttf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
