name: projectunity
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cached_network_image: ^3.3.1
  cupertino_icons:
  cloud_firestore: ^4.5.2
  collection: ^1.17.0
  connectivity_plus: ^3.0.5
  device_info_plus: ^8.2.1
  equatable: ^2.0.5
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.3.1
  firebase_storage: ^11.1.1
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.9
  get_it: ^7.3.0
  google_sign_in: ^6.2.1
  go_router: ^13.0.1
  http: ^1.2.0
  intl: ^0.18.1
  injectable: ^2.1.1
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  oauth2: ^2.0.2
  package_info_plus: ^5.0.1
  simple_gesture_detector:
  rxdart: ^0.27.7
  shared_preferences: ^2.1.1
  sticky_headers: ^0.3.0+2
  table_calendar: ^3.0.7
  url_launcher: ^6.1.11
  window_to_front: ^0.0.3







dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  flutter_gen_runner:





flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter_regular.ttf
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_light.ttf
        - asset: assets/fonts/inter_medium.ttf
        - asset: assets/fonts/inter_semi_bold.ttf


    - family: poppins
      fonts:

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic

