name: IOS Build

#on: workflow_dispatch
on: push

jobs:
  ios_build_ipa:
    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.6
          cache: 'gradle'


      - uses: subosito/flutter-action@v2
        name: Set up Flutter SDK
        with:
          flutter-version: 3.7.7
          channel: 'stable'
          cache: true

      - name: Retrieve the secret and decode it to a file
        env:
          DESKTOP_CREDENTIALS_BASE64: ${{ secrets.DESKTOP_CREDENTIALS_BASE64 }}
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}
          GOOGLE_SERVICES_PLIST_IOS_BASE64: ${{ secrets.GOOGLE_SERVICES_PLIST_IOS_BASE64 }}

        run: |
          echo $DESKTOP_CREDENTIALS_BASE64 | base64 --decode > lib/desktop_credentials.dart
          echo $FIREBASE_OPTIONS_BASE64 | base64 --decode > lib/firebase_options.dart
          echo $GOOGLE_SERVICES_PLIST_IOS_BASE64 | base64 --decode > ios/Runner/GoogleService-Info.

      - name: Generate build
        run: |
          cd ios
          chmod +x ios_dist_profile_script.sh && ./ios_dist_profile_script.sh
          chmod +x ios_dist_certificate_script.sh && ./ios_dist_certificate_script.sh
          source ~/.zshrc
          flutter pub get
          ARCHIVE_PATH="$HOME/Library/Developer/Xcode/Archives/ProjectUnity/${CI_COMMIT_SHA}/${CI_JOB_ID}.xcarchive"
          xcodebuild -workspace Runner.xcworkspace -scheme "Runner" clean archive -sdk iphoneos -archivePath $ARCHIVE_PATH | xcpretty --color
          cd ..
          rm -rf $ARCHIVE_PATH
          echo "Build successfully"
