name: Test and Lint job

on: push


jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - uses: subosito/flutter-action@v2
        name: Set up Flutter SDK
        with:
          flutter-version: 3.7.7
          channel: 'stable'

      - name: Decode files
        uses: timheuer/base64-to-file@v1.0.3
        with:
          secret: ${{ secrets.DESKTOP_CREDENTIALS_BASE64 }}
          filename: desktop_credentials.dart
          destination-path: ~/lib


        run: |
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 -di > android/app/google-services.json
          echo "$GOOGLE_SERVICES_PLIST_IOS_BASE64" | base64 -di > ios/Runner/GoogleService-Info.plist
          echo "$GOOGLE_SERVICES_PLIST_MACOS_BASE64" | base64 -di > macos/Runner/GoogleService-Info.plist
          echo "$WEB_INDEX_HTML_BASE64" | base64 -di > web/index.html
          flutter clean
          flutter pub get
          dart analyze --fatal-infos
